name: Build NCurses

on: [workflow_dispatch]

jobs:
  ubuntu-x64:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone NCurses Master
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: Make
        run: |
         ./configure \
            --prefix=/usr \
            --enable-pc-files \
            --without-cxx \
            --without-ada \
            --enable-widec \
            --with-pkg-config-libdir=/usr/lib/pkgconfig \
            --with-shared \
            --enable-sigwinch \
            --with-versioned-syms \
            --with-xterm-kbs=del \
            --enable-warnings \
            --enable-assertions \
            --disable-macros \
            --without-manpages
          make
          mv lib/libncursesw.so lib/libncursesw-x64.so
      - name: Upload Artifacts (1)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'lib/libncursesw-x64.so'
          if-no-files-found: error
          
  macos-x64:
    if: ${{ false }}
    runs-on: macOS-latest
    steps:
      - name: Clone NCurses Master
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: Make
        run: |
         ./configure \
            --prefix=/usr \
            --enable-pc-files \
            --without-cxx \
            --without-ada \
            --enable-widec \
            --with-pkg-config-libdir=/usr/lib/pkgconfig \
            --with-shared \
            --enable-sigwinch \
            --with-versioned-syms \
            --with-xterm-kbs=del \
            --enable-warnings \
            --enable-assertions \
            --disable-macros \
            --without-manpages \
            --with-gpm=no
          make
          mv lib/libncursesw.dylib lib/libncursesw-x64.dylib
      - name: Upload Artifacts (1)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'lib/libncursesw-x64.dylib'
          if-no-files-found: error
          
  windows-x64:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Clone NCurses Master
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: Install MSys2
        uses: msys2/setup-msys2@v2
        with:
          install: gcc make diffutils msys2-w32api-headers msys2-w32api-runtime
      - name: Make
        run: |
          ./configure \
            --prefix=/mingw64 \
            --without-cxx \
            --without-ada \
            --enable-warnings \
            --enable-assertions \
            --enable-exp-win32 \
            --enable-ext-funcs \
            --disable-home-terminfo \
            --disable-echo \
            --disable-getcap \
            --disable-hard-tabs \
            --disable-leaks \
            --disable-macros \
            --disable-overwrite \
            --enable-opaque-curses \
            --enable-opaque-panel \
            --enable-opaque-menu \
            --enable-interop \
            --enable-exp-win32 \
            --enable-database \
            --with-progs \
            --without-libtool \
            --enable-pc-files \
            --with-shared \
            --with-normal \
            --without-debug \
            --enable-widec \
            --with-fallbacks=ms-terminal \
            --without-manpages
          make
          mv lib/libncursesw6.dll lib/libncursesw-x64.dll
      - name: Upload Artifacts (2)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'lib/libncursesw-x64.dll'
          if-no-files-found: error
