name: Build PDCurses

on: [workflow_dispatch]

jobs:
  windows-x64:
    runs-on: windows-2019

    steps:
      - name: Clone PDCurses Master
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master
      - name: Make
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd wincon
          nmake WIDE=Y DLL=Y -f Makefile.vc
          ren pdcurses.dll pdcurses-wincon-x64.dll
        shell: cmd
      - name: Upload Artifacts (2)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'wincon/*.dll'
          if-no-files-found: error
          
  push-to-repo:
    runs-on: ubuntu-latest
    needs: [windows-x64]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: lib
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: native-lib-updates
          create_branch: true
          push_options: '--force'
          commit_user_name: Alexandru Ciobanu [bot]
          commit_user_email: alex+git[bot]@ciobanu.org
          commit_author: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          commit_message: (chore) Update PDCursesMod native libraries.
