name: Build PDCursesMod

on: [workflow_dispatch]

jobs:
  ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Clone PDCursesMod master
        uses: actions/checkout@master
        with:
          repository: Bill-Gray/PDCursesMod
          ref: refs/heads/master
      - name: make
        run: |
         cd vt
         make WIDE=Y DLL=Y CHTYPE_32=Y  
         cd ../fb
         make WIDE=Y DLL=Y CHTYPE_32=Y
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: '*/libpdcurses.so'

