name: Build PDCurses

on: [workflow_dispatch]

jobs:
  windowx-x64:
    runs-on: windows-2019

    steps:
      - name: Clone PDCursesMod Master
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master
      - name: Make
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd wincon
          nmake WIDE=Y DLL=Y CHTYPE_32=Y -f Makefile.vc
          ren pdcurses.dll pdcurses-wincon-x64.dll
        shell: cmd
      - name: Upload Artifacts (2)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'wincon/*.dll'
          if-no-files-found: error
