name: Build PDCurses

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 1 1-12 *'

jobs:
  windows-x64:
    runs-on: windows-2019

    steps:
      - name: Clone PDCurses Master
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master
      - name: Make
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd wincon
          nmake WIDE=Y DLL=Y -f Makefile.vc
          ren pdcurses.dll libpdcurses-wincon-x64.dll
        shell: cmd
      - name: Upload Artifacts (1)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'wincon/*.dll'
          if-no-files-found: error
          
  create-pr:
    runs-on: ubuntu-latest
    needs: [windows-x64]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: lib/pdcurses
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: (chore) Update PDCurses native libraries.
          committer: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          author: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          title: Update PDCurses native library to latest master.
          body: This is an auto-generated PR with native library updates.
          delete-branch: true
          labels: dependencies
          assignees: pavkam
          branch: pdcurses-lib-update
