name: Build PDCurses

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 1 1-12 *'

jobs:
  ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Clone PDCurses Master
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master
      - name: Install SDL1 and SDL2
        run: |
         sudo apt install libsdl1.2-dev libsdl-ttf2.0-dev libsdl2-dev libsdl2-ttf-dev
      - name: Make SDL1
        run: |
         cd sdl1
         make WIDE=Y DLL=Y CHTYPE_32=Y
         mv pdcurses.so libpdcurses-sdl1-x64.so
      - name: Make SDL2
        run: |
         cd sdl2
         make WIDE=Y DLL=Y CHTYPE_32=Y
         mv pdcurses.so libpdcurses-sdl2-x64.so
      - name: Upload Artifacts (1)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'sdl1/*.so'
          if-no-files-found: error
      - name: Upload Artifacts (2)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'sdl2/*.so'
          if-no-files-found: error
          
  windows-x64:
    runs-on: windows-2019

    steps:
      - name: Clone PDCurses Master
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master
      - name: Make
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd wincon
          nmake WIDE=Y DLL=Y -f Makefile.vc
          ren pdcurses.dll libpdcurses-wincon-x64.dll
        shell: cmd
      - name: Upload Artifacts (2)
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: 'wincon/*.dll'
          if-no-files-found: error
          
  create-pr:
    runs-on: ubuntu-latest
    needs: [windows-x64, ubuntu-x64]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: lib/pdcurses
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: (chore) Update PDCurses native libraries.
          committer: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          author: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          title: Update PDCurses native library to latest master.
          body: This is an auto-generated PR with native library updates.
          delete-branch: true
          labels: dependencies
          assignees: pavkam
          branch: pdcurses-lib-update
